syntax = "LuaJIT"
column_width = 100
line_endings = "Unix"
indent_type = "Spaces" # Can switch this later if anyone needs tabs for accessibility :), Truth is, i like tabs now, but i have my editor configured on spaces, and i dont want to mess with that configuration again i dont like vim for this
indent_width = 4
quote_style = "AutoPreferSingle"
call_parentheses = "None"
collapse_simple_statement = "ConditionalOnly" # I find this really annoying on functions
space_after_function_names = "Never"
